### ISSUE TITLE
能做到左滑进入下一张卡片，右滑回到上一张卡片的效果吗

### ISSUE THREAD

**Issue by caprice** [adgvcxz/CardLayoutManager#11]
如题，需求依然要求类似的卡片层叠布局，但是要左滑进入下一张卡片，右滑回到上一张卡片。谢谢。

**Comment by adgvcxz** [comment]
不好意思，这个需求目前是不支持的。

**Comment by caprice** [comment]
那么如何修改可以支持呢，能给个建议吗

**Comment by adgvcxz** [comment]
具体不太清楚你的需求

在左滑进入下一张卡片的时候，当前卡片你是需要像库一样跟着手上下左右移动，然后滑出去。还是像ViewPager一样只能横向或者竖向滑动？

在右滑进入上一张卡片的时候，被滑动的卡片不在屏幕上也是需要跟着手指上下左右滑动吗？

**Comment by caprice** [comment]
多谢回答。需求像viewpager一样左右滑动，右滑下一张，左滑上一张。只是多了卡片层叠的效果。

**Comment by adgvcxz** [comment]
那样就用viewpager就可以做了啊
参考这个就可以了 https://github.com/ToxicBakery/ViewPagerTransforms
