### ISSUE TITLE
Disable scrolling from users?

### ISSUE THREAD

**Issue by njovy** [adgvcxz/CardLayoutManager#2]
Thank you for this awesome library.

I was wondering if there is way to disable scrolling from users so my app is the only one that can scroll to a certain position upon user's interactions. 

Any advice would be much appreciated.

**Comment by adgvcxz** [comment]
@njovy Thranks, I don't understand the effect you want.
You want the card to scroll automatically to the specified position when ACTION_UP
Or
This card can scroll when scrolling in the specified area

**Comment by njovy** [comment]
@adgvcxz I want a card to be scrolled to a specified position only by an app not by users. When it is scrolled, users can't touch or interfere
