### ISSUE TITLE
Support of translation on different sides.

### ISSUE THREAD

**Issue by sikrinick** [adgvcxz/CardLayoutManager#4]
Are you planning to add support of elevation for other sides?
Not only bottom, but also, for top and right?

**Comment by adgvcxz** [comment]
@sikrinick You can set the CardView elevation

**Comment by sikrinick** [comment]
@adgvcxz I mean, there is elevation on bottom side, but I would prefer to have it, for example, on left, top or right side.
I made a workaround and I can send you pull request, if you don't mind.

Also, is it possible to allow set action for different scroll movements? For example, scroll to next on left-to-right and scroll to previous on right-to-left without some onTouch code?

**Comment by adgvcxz** [comment]
@sikrinick Yeah
You can send your pull request.

scroll to next on left-to-right and scroll to previous on right-to-left without some onTouch code?

I think it needs to override ```fillChild```
